apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    app: admin
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: agencyservice
  namespace: caritas
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: agencyservice
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    clickhouse.altinity.com/Service: host
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: signoz-clickhouse
    clickhouse.altinity.com/cluster: cluster
    clickhouse.altinity.com/namespace: caritas
    clickhouse.altinity.com/object-version: f3ce64fc3dc6f259619c2e2d8bab1e24bbcf01f3
    clickhouse.altinity.com/replica: '0'
    clickhouse.altinity.com/shard: '0'
    helm.sh/chart: clickhouse-24.1.18
  name: chi-signoz-clickhouse-cluster-0-0
  namespace: caritas
  ownerReferences:
  - apiVersion: clickhouse.altinity.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: ClickHouseInstallation
    name: signoz-clickhouse
    uid: ca275704-94ea-462f-9d26-9f670658fbc4
spec:
  ports:
  - name: tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
  - name: interserver
    port: 9009
    protocol: TCP
    targetPort: 9009
  publishNotReadyAddresses: true
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: signoz-clickhouse
    clickhouse.altinity.com/cluster: cluster
    clickhouse.altinity.com/namespace: caritas
    clickhouse.altinity.com/replica: '0'
    clickhouse.altinity.com/shard: '0'
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cob-proxy
  name: cob-proxy
  namespace: caritas
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: cob-proxy
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: consultingtypeservice
  namespace: caritas
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: consultingtypeservice
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: element
  namespace: caritas
spec:
  ports:
  - port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: element
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9001
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-temp
  namespace: caritas
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-temp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: health-dashboard
  namespace: caritas
spec:
  ports:
  - name: http
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: health-dashboard
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: host-nginx-proxy
  namespace: caritas
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-jvb
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: rtp
    port: 10000
    protocol: UDP
    targetPort: 10000
  - name: tcp-fallback
    port: 4443
    protocol: TCP
    targetPort: 4443
  selector:
    app: jitsi-meet
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-meet
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: jitsi-meet
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-prosody
  namespace: caritas
spec:
  ports:
  - name: xmpp-client
    port: 5222
    protocol: TCP
    targetPort: 5222
  - name: bosh
    port: 5280
    protocol: TCP
    targetPort: 5280
  - name: component
    port: 5347
    protocol: TCP
    targetPort: 5347
  selector:
    app: jitsi-meet
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: caritas
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: keycloak
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: livekit
  name: livekit
  namespace: caritas
spec:
  ports:
  - name: http
    port: 7880
    protocol: TCP
    targetPort: 7880
  selector:
    app: livekit
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: livekit-token-service
  name: livekit-token-service
  namespace: caritas
spec:
  ports:
  - name: http
    port: 3010
    protocol: TCP
    targetPort: 3010
  selector:
    app: livekit-token-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: liveservice
  namespace: caritas
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: liveservice
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: caritas
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-postgres-service
  namespace: caritas
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: matrix-postgres
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: matrix-synapse
  name: matrix-synapse
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: client-api
    port: 8008
    protocol: TCP
    targetPort: 8008
  - name: federation
    port: 8009
    protocol: TCP
    targetPort: 8009
  selector:
    app: matrix-synapse
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: messageservice
  name: messageservice
  namespace: caritas
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: messageservice
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: caritas
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: caritas
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: management
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: caritas
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-commander
  name: redis-commander
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 9021
    protocol: TCP
    targetPort: 8081
  selector:
    app: redis-commander
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: caritas
spec:
  ports:
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: redis-exporter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-exporter
  name: redis-exporter-metrics
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: metrics
    port: 9020
    protocol: TCP
    targetPort: 9121
  selector:
    app: redis-exporter
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-headless
  namespace: caritas
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisinsight
  name: redisinsight
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: redisinsight
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat
  namespace: caritas
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rocketchat
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: signoz
    app.kubernetes.io/version: v0.97.1
    helm.sh/chart: signoz-0.96.0
  name: signoz
  namespace: caritas
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: http-internal
    port: 8085
    protocol: TCP
    targetPort: http-internal
  - name: opamp-internal
    port: 4320
    protocol: TCP
    targetPort: opamp-internal
  selector:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    clickhouse.altinity.com/Service: chi
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: signoz-clickhouse
    clickhouse.altinity.com/namespace: caritas
    clickhouse.altinity.com/object-version: dea704f67fbabf6dc9e17fb064e7c5fa9d88fa66
    helm.sh/chart: clickhouse-24.1.18
  name: signoz-clickhouse
  namespace: caritas
  ownerReferences:
  - apiVersion: clickhouse.altinity.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: ClickHouseInstallation
    name: signoz-clickhouse
    uid: ca275704-94ea-462f-9d26-9f670658fbc4
spec:
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
  - name: tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: signoz-clickhouse
    clickhouse.altinity.com/namespace: caritas
    clickhouse.altinity.com/ready: 'yes'
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    clickhouse.altinity.com/chop: 0.21.2
    helm.sh/chart: clickhouse-24.1.18
  name: signoz-clickhouse-operator-metrics
  namespace: caritas
spec:
  ports:
  - name: signoz-clickhouse-operator-metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: clickhouse
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: signoz
    app.kubernetes.io/version: v0.97.1
    helm.sh/chart: signoz-0.96.0
  name: signoz-otel-collector
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: jaeger-grpc
    port: 14250
    protocol: TCP
    targetPort: jaeger-grpc
  - name: jaeger-thrift
    port: 14268
    protocol: TCP
    targetPort: jaeger-thrift
  - name: logsheroku
    port: 8081
    protocol: TCP
    targetPort: logsheroku
  - name: logsjson
    port: 8082
    protocol: TCP
    targetPort: logsjson
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: metrics
  - name: otlp
    port: 4317
    protocol: TCP
    targetPort: otlp
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: otlp-http
  selector:
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-0.0.1
  name: signoz-zookeeper
  namespace: caritas
spec:
  ports:
  - name: tcp-client
    port: 2181
    protocol: TCP
    targetPort: client
  - name: tcp-follower
    port: 2888
    protocol: TCP
    targetPort: follower
  - name: tcp-election
    port: 3888
    protocol: TCP
    targetPort: election
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: zookeeper
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-0.0.1
  name: signoz-zookeeper-headless
  namespace: caritas
spec:
  ports:
  - name: tcp-client
    port: 2181
    protocol: TCP
    targetPort: client
  - name: tcp-follower
    port: 2888
    protocol: TCP
    targetPort: follower
  - name: tcp-election
    port: 3888
    protocol: TCP
    targetPort: election
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: zookeeper
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-0.0.1
  name: signoz-zookeeper-metrics
  namespace: caritas
spec:
  ports:
  - name: tcp-metrics
    port: 9141
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: zookeeper
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: status-page
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: status-page
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storybook
  name: storybook
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 6006
    protocol: TCP
    targetPort: 80
  selector:
    app: storybook
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tenantservice
  namespace: caritas
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: tenantservice
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: uploadservice
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: uploadservice
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: caritas
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: userservice
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: videoservice
  namespace: caritas
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: videoservice
  sessionAffinity: None
    type: NodePort
